steps:
    - name: ubuntu
      args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
    - name: gcr.io/cloud-builders/gsutil
      args:
        - '-m'
        - 'rsync'
        - '-d'
        - '-r'
        - 'files'
        - 'gs://test-cloudbuild-jfunes/files' 